from utils.src import *

clear_cache()
clear_output()
st.sidebar.header("**THERMAL BALANCE CALCULATOR**")
st.sidebar.divider()
st.sidebar.image(r"utils/lab_banner.png", width=300)
add_page_title()


st.header("Title")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.markdown("Text text text text text text text text text text text text text text text text text text")
st.header("Title")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.header("Title")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.markdown("Text text text text text text text text text text text text text text text text text text")
st.header("Title")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.header("Title")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.markdown("Text text text text text text text text text text text text text text text text text text")
st.header("Title")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.header("Title")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.markdown("Text text text text text text text text text text text text text text text text text text")
st.header("Title")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")
st.markdown("Text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text")